### ISSUE TITLE
how to use --gpioPin without any hardware define

### ISSUE THREAD

**Issue by dony71** [Psychokiller1888/snipsLedControl#16]
I don't have any hardware define in hardware support(Respeaker 2, Respeaker 4, Respeaker Mic Array V2, NeoPixels ring, Matrix Voice), instead I'm using USB microphone + 2 LEDs connected to GPIO 
How to use --gpioPin only? Default --hardware=respeaker2, I cannot assign --hardware=none
Any example?

**Comment by Psychokiller1888** [comment]
You can't, as there's no support for direct gpio. But you can make the interface

**Comment by dony71** [comment]
Any plan for you to make this interface?
I'm not good in programming

**Comment by Psychokiller1888** [comment]
I can do it, yes

**Comment by Psychokiller1888** [comment]
I have started implementing something, on dev 1.5 branch. Should be usable by this evening

**Comment by Psychokiller1888** [comment]
Version 1.5 released with a working setup for gpio leds

Use arguments `--hardware=puregpio --pureGpioPinout=[YOUR, LEDS, PIN, NUMBERS]`

By default it's wired as cathode to ground and anode to resistor and gpio. You can invert it if you want but use the `--activeHigh=False` argument
