### ISSUE TITLE
Matrix Voice IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by jbperrin88** [Psychokiller1888/snipsLedControl#17]
Hi there !

First of all , thanks you for all the stuff you give to snips community !! That amazing ! 

Like a tell you on discord yesterday , i got some strange behavior with snips led control and matrix voice 

First log with the initial error 
https://pastebin.com/HuaV0rKD

I've made the modification you give to me
` def setPixel(self, ledNum, red, green, blue, white):
        ledValue = io_pb2.LedValue()
        ledValue.red   = red
        ledValue.green = green
        ledValue.blue  = blue
        ledValue.white = white
        print(ledNum)
        print(self._numLeds)
        if ledNum < len(self._colors):
            self._colors[ledNum] = ledValue
        else:
            self._logger.warning("Tried to access a led number that doesn't exist")`

Result with google pattern :
https://pastebin.com/WecihHyX
Look like the num_leds is multiply by 2 somewhere .... 

Result with alexa pattern : 
https://pastebin.com/ddNLfF4a

I remove some line from both alexa and google export (pastebin failed without removing it ...)

If you need some help, please ask !

**Comment by Psychokiller1888** [comment]
By looking at the timestamps, I take it as the wakeup animation right after start works, but it fails when you try to call your assistant?

**Comment by jbperrin88** [comment]
Nope ... The startup annulation looks good . It is the wakeup pattern just after hotwire is detected

**Comment by jbperrin88** [comment]
Hotword

**Comment by Psychokiller1888** [comment]
Yeah, that's what I said...

**Comment by jbperrin88** [comment]
Hum .... Sorrrrrry I've read to fast and I'm French haha fail ! 

Thanks you .

I'll try soon. ;B
