### ISSUE TITLE
Respeaker Core v2 not working with version 1.6

### ISSUE THREAD

**Issue by hpposch** [Psychokiller1888/snipsLedControl#23]
**Do not remove fields, answer them, otherwise your bug will be reported as invalid and closed**

**How I did start SLC, with what arguments**
sudo python main.py --mqttServer=127.0.0.1 --hardware=respeakerCoreV2 --defaultBrightness=70 --debug h

**Led device name**
respeakerCoreV2

**The bug**
I just do not see the leds flashing i tried to start the script with multiple options like mqttPort but nothing changed.

**To Reproduce**
just execute: sudo python main.py --mqttServer=127.0.0.1 --hardware=respeakerCoreV2 --defaultBrightness=70 --debug h

**DEBUG LOG**
sudo python main.py --mqttServer=127.0.0.1 --hardware=respeakerCoreV2 --defaultBrightness=70 --debug h

Starting Snips Led Control v. 1.6.1
Initializing SnipsLedControl
Loading configurations
Loaded 9 hardware references
- Mqtt server set to 127.0.0.1
- Mqtt port set to 1883
- Client id set to default
- Hardware set to Respeaker Core v2
- Using google as pattern with 12 leds
Initializing leds controller
/usr/local/lib/python2.7/dist-packages/gpiozero/devices.py:452: PinFactoryFallback: Falling back from rpigpio: This module can only be run on a Raspberry Pi!
  'Falling back from %s: %s' % (name, str(e))))
/usr/local/lib/python2.7/dist-packages/gpiozero/devices.py:452: PinFactoryFallback: Falling back from rpio: No module named RPIO
  'Falling back from %s: %s' % (name, str(e))))
/usr/local/lib/python2.7/dist-packages/gpiozero/devices.py:452: PinFactoryFallback: Falling back from pigpio: No module named pigpio
  'Falling back from %s: %s' % (name, str(e))))
/usr/local/lib/python2.7/dist-packages/gpiozero/devices.py:452: PinFactoryFallback: Falling back from native: unable to determine RPi revision
  'Falling back from %s: %s' % (name, str(e))))
Device not using gpio zero, ignore power
Snips Led Control started
On hotword triggered
On listen triggered
On think triggered
On say triggered
On hotword toggle on triggered

**Comment by Psychokiller1888** [comment]
To me it looks like you haven't run the hardware installation, as gpiozero is uninstalled for respeaker core v2 during SLC install

`pip uninstall -y gpiozero`

**Comment by hpposch** [comment]
ok so when i ask to install respeaker core v2 i must select yes?

**Comment by hpposch** [comment]
or can you please tell me the steps to enable the leds :)

**Comment by Psychokiller1888** [comment]
just run the command I gave you to get rid of gpiozero

**Comment by hpposch** [comment]
it says:
pip uninstall -y gpiozero
Cannot uninstall requirement gpiozero, not installed

**Comment by hpposch** [comment]
It is working now on my device

**Comment by Psychokiller1888** [comment]
And what did you do?

**Comment by hpposch** [comment]
I just followed your instruction.
And today, after a reboot suddenly everything worked.
