### ISSUE TITLE
Feature Request: For Respeaker Mic Array v2 make volume control available

### ISSUE THREAD

**Issue by herrwusel** [Psychokiller1888/snipsLedControl#27]
It would be nice to control the volume over SLC as well.
http://wiki.seeedstudio.com/ReSpeaker_Mic_Array_v2.0/#tuning

**Comment by herrwusel** [comment]
If you are using the audio output of the mic array, you are able to set a volume through pixel_ring. SLC might as well do that. If you don't set it manually, it is 100%.

**Comment by Psychokiller1888** [comment]
Ok, you have 2 new topics:

- 'hermes/leds/vadLed' => payload['state'] int (0-1)
- 'hermes/volume/set' => payload['volume'] int (hardware min - hardware max)

**Comment by Psychokiller1888** [comment]
Did this do the trick?

**Comment by OnkelBuTscH** [comment]
I do not know exactly what I have to do.
Could you please show me an example how I can change the volume?

**Comment by Psychokiller1888** [comment]
Just publish a mqtt topic on `hermes/volume/set` with a payload containing volume for the desired volume level

**Comment by OnkelBuTscH** [comment]
thank you, it works
