### ISSUE TITLE
Google AIY TTS

### ISSUE THREAD

**Issue by oguh22** [Psychokiller1888/snipsLedControl#33]
Hello @Psychokiller1888 !

First, thanks a lot for your job around Snips :)
I just test snipsLedControl on my environnement :
- on my Snips satellite using a respeaker 2 it's working fine :)
- on my Google AIY kit, when I use the snips TTS feature, the light switch on blue but never switch off at the end of the TTS. I need to say "hey snips" and wait for the timeout to switch of the light

Other question,
I am not a developper sorry :s 
how can I modiffy the code to be able to use the button on my Google AIY and my respeaker to start Snips as if I said "hey snips" ?

Regards,

Hugo

**Comment by Psychokiller1888** [comment]
Hello!

Please start in debug mode as asked by the bug report template and paste the output here. If it doesn't turn off most likely an event is not caught
