### ISSUE TITLE
Can't Connect to MQTT server?

### ISSUE THREAD

**Issue by JC-Mac** [Psychokiller1888/snipsLedControl#53]
Hi, 

Trying this out.  Running snips-satelite on a pieZero with remote snips-base and remote mqtt (tls & uname and pwd auth)

**How I did start SLC, with what arguments**
python main.py --debug=True

**Led device name**
"ReSpeaker 2"

**The bug**
Fails to connect to MQTT server - Default settings from Snips.toml are being used.  PieZero is a Snips-Satelite running: Snips-Satelite and Snips-Hotword.  MQTT server is remote and uses TLS on 8443 and a username and password.  Snips.toml settings are correct since the snips-satelite is working properly - talks to mqtt and base and interacts successfully with HA.

**Debug output**
python3 main.py --debug=True
Starting Snips Led Control v. 1.9.10
Initializing SnipsLedControl
Loading configurations
Loaded 12 hardware references
- Mqtt server set to mqtt.<mydomain>.com:8883
- Mqtt port set to 8883
- Mqtt username set to homeassistant
- Mqtt password set to "hidden"
- Client id set to zero1
- Hardware set to ReSpeaker 2
- Using google as pattern with 3 leds
Initializing leds controller
Couldn't connect to mqtt, aborting

**To Reproduce**
Run in debug mode as above.

**Comment by Psychokiller1888** [comment]
It's because I never implemented TLS support
