### ISSUE TITLE
Button behavior choice

### ISSUE THREAD

**Issue by Platup** [Psychokiller1888/snipsLedControl#54]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it would be nice if the chosen card has a supported button, to prompt for the button behavior like mute or wake.

**Describe the solution you'd like**
During install, if the selected card has a supported button then prompt for one of two behaviors.  1.  Mute on/off  Or 2. Activate listening
Also, then the button wouldn't have to be tied to a particular pattern.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by JojoSs75** [comment]
Superb idea, the button being integrated in Respeaker, it could change the current pattern.  for example: current pattern "google" is pressed and SCL goes to "alexa" one rapuis and SCL goes to "projectalice".  and same with "puregpio" for modules that do not have buttons.

**Comment by Psychokiller1888** [comment]
The buttons are available to customise when you create your own pattern. onButton1 to onButton6
