### ISSUE TITLE
 respeakerMicArrayV2 - Device or resource busy

### ISSUE THREAD

**Issue by akashha** [Psychokiller1888/snipsLedControl#58]
**Do not remove fields, answer them, otherwise your bug will be reported as invalid and closed**

**How I did start SLC, with what arguments**
python3 main.py --hardware=respeakerMicArrayV2 --pattern=google --debug=True

**Led device name**
respeakerMicArrayV2

**The bug**

When i run the process, i have an error "arecord: main:828: audio open error: Device or resource busy" but in my process, i haven't any open record.

> pi@raspberrypi:$ ps -A | grep record
>  6059 ?        00:00:00 arecord <defunct>
> pi@raspberrypi:$

The 6059 pid is snipsLedControl child :
> root      6045  109  2.7  91704 26552 ?        Ssl  22:20   7:30 /home/pi/snipsLedControl_v1.9.11/venv/bin/python3 main.py --hardware=respeakerMicArrayV2 --pattern=google --debug=True
> root      6059  0.0  0.0      0     0 ?        Z    22:20   0:00  \_ [arecord] <defunct>

An idea ? 
Thank you in advance.

**Debug output**

Oct 25 22:20:34 raspberrypi python3[6045]: Starting Snips Led Control v. 1.9.11
Oct 25 22:20:34 raspberrypi python3[6045]: Initializing SnipsLedControl
Oct 25 22:20:34 raspberrypi python3[6045]: Loading configurations
Oct 25 22:20:34 raspberrypi python3[6045]: Loaded 12 hardware references
Oct 25 22:20:34 raspberrypi python3[6045]: - Mqtt server set to localhost
Oct 25 22:20:34 raspberrypi python3[6045]: - Mqtt port set to 1883
Oct 25 22:20:34 raspberrypi python3[6045]: - Client id set to default
Oct 25 22:20:34 raspberrypi python3[6045]: - Hardware set to ReSpeaker Mic array v2
Oct 25 22:20:34 raspberrypi python3[6045]: - Using google as pattern with 12 leds
Oct 25 22:20:34 raspberrypi python3[6045]: Initializing leds controller
Oct 25 22:20:35 raspberrypi python3[6045]: Hardware is DOA capable
Oct 25 22:20:35 raspberrypi python3[6045]: Starting DOA
Oct 25 22:20:35 raspberrypi python3[6045]: Snips Led Control started
Oct 25 22:20:35 raspberrypi python3[6045]: arecord: main:828: audio open error: Device or resource busy

**To Reproduce**

Start snipsledcontrol.service

**Comment by Pittermaennchen** [comment]
Was there any solution to this? I am running into the same problem with my respeaker 4-mic-array.
