### ISSUE TITLE
No MQTT connection with predefined MQTT Server in snips.toml (Solution provided)

### ISSUE THREAD

**Issue by SpaceMaster85** [Psychokiller1888/snipsLedControl#60]
**Do not remove fields, answer them, otherwise your bug will be reported as invalid and closed**

**How I did start SLC, with what arguments**
./venv/bin/python3 main.py --debug=True --hardware=respeaker2

**Led device name**
The name of the device such as "ReSpeaker 2" or "Matrix Voice"
Raspberry Pi Zero with Respeacker 2 Mic hat

**The bug**
 I have following snips.toml:
```
[snips-common]
# bus = "mqtt"
mqtt = "192.168.0.10:9883"
# audio = ["+@mqtt"]
# assistant = "/usr/share/snips/assistant"
# user_dir = "/var/lib/snips"

## MQTT authentication
mqtt_username = "snips_wohnzimmer"
mqtt_password = "xxxxxx"
```

Starting snips led control with debug option shows that the script can't connect to mqtt server.
Problem is the wrong mqttserver attribute because it contains the ip AND the port (as defined in snips.toml)

**Debug output**
Follow instructions on https://github.com/Psychokiller1888/snipsLedControl/wiki/Run-in-debug-mode
And paste the output

```
Starting Snips Led Control v. 1.9.11
Initializing SnipsLedControl
Loading configurations
Loaded 12 hardware references
- Mqtt server set to 192.168.0.112:9883
- Mqtt port set to 9883
- Client id set to wohnzimmer
- Hardware set to ReSpeaker 2
- Using google as pattern with 3 leds
Initializing leds controller
Couldn't connect to mqtt, aborting
```

**To Reproduce**
Steps to reproduce the behavior
Define IP and Port in snips.toml
Start snipsledcontrol
Mqtt connect fails

**SOLUTION**

File models/SnipsLedControl.py
Line 99                                        
`self._mqttServer, self._mqttPort = self._snipsConfigs['snips-common']['mqtt'].split(':')`

Now we are not only taking the mqtt port from the snips.toml file but also use the corrct mqtt server string.

After the change snipsledcontrol is connection correct to mqtt server.

**Comment by Psychokiller1888** [comment]
Thank you!
